// StockLens PDF Upload — self-injects upload button

function tryInjectPdfButton() {
  if (document.getElementById('pdf-upload')) return true;
  const bizLabel = [...document.querySelectorAll('p.section-label')].find(el => el.textContent.includes('Business Understanding'));
  if (!bizLabel) return false;
  const d = document.createElement('div');
  d.style.cssText = 'margin:0 16px 12px';
  d.innerHTML = '<label for="pdf-upload" id="pdf-upload-label" style="display:block;width:100%;padding:12px 16px;background:var(--surface);border:2px dashed var(--border2);border-radius:var(--r);text-align:center;cursor:pointer;color:var(--text2);font-size:13px;font-family:inherit">📄 Upload StockLens Analysis PDF<span style=\'display:block;font-size:11px;margin-top:3px;color:var(--text3)\'>Generated by Claude — auto-fills checklist</span></label><input type="file" id="pdf-upload" accept=".pdf" style="display:none" onchange="handlePdfUpload(this)">';
  bizLabel.parentNode.insertBefore(d, bizLabel);
  return true;
}

function initPdfUpload() {
  if (!tryInjectPdfButton()) {
    const obs = new MutationObserver(() => { if (tryInjectPdfButton()) obs.disconnect(); });
    obs.observe(document.body, { childList: true, subtree: true });
  }
  document.addEventListener('click', () => setTimeout(tryInjectPdfButton, 400));
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initPdfUpload);
} else { initPdfUpload(); }

async function handlePdfUpload(input) {
  const file = input.files[0]; if (!file) return;
  const label = document.getElementById('pdf-upload-label');
  label.textContent = 'Reading PDF...';
  try {
    pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://unpkg.com/pdfjs-dist@3.11.174/build/pdf.worker.min.js';
    const pdf = await pdfjsLib.getDocument({ data: await file.arrayBuffer() }).promise;

    // Extract all text strings from every page
    let allStrings = [];
    for (let i = 1; i <= pdf.numPages; i++) {
      const pg = await pdf.getPage(i);
      const tc = await pg.getTextContent();
      tc.items.forEach(item => { if (item.str && item.str.trim()) allStrings.push(item.str.trim()); });
    }
    const txt = allStrings.join(' ');

    // Find data block — lenient search
    const s = txt.indexOf('STOCKLENS DATA');
    const e = txt.indexOf('END DATA');
    if (s === -1 || e === -1) {
      showToast('No StockLens data block found in PDF');
      label.innerHTML = '📄 Upload StockLens Analysis PDF<span style="display:block;font-size:11px;margin-top:3px;color:var(--text3)">Generated by Claude</span>';
      return;
    }

    const blockContent = txt.substring(s + 14, e).trim();

    // Use matchAll to find all keys and extract values between them
    const keyPattern = /\b(STOCK|SECTOR|BIZ_MODEL|MAIN_RISK|hs\d+_\d+|p\d+_\d+)\s*:/g;
    const matches = [...blockContent.matchAll(keyPattern)];

    if (matches.length === 0) {
      showToast('Found data block but could not parse items');
      return;
    }

    let n = 0;
    window.aiFilledItems = {};

    matches.forEach((match, i) => {
      const key = match[1];
      const valueStart = match.index + match[0].length;
      const valueEnd = i < matches.length - 1 ? matches[i + 1].index : blockContent.length;
      const value = blockContent.substring(valueStart, valueEnd).trim();

      if (key === 'STOCK') { document.getElementById('cl-stock').value = value; return; }
      if (key === 'SECTOR') {
        const sel = document.getElementById('cl-sector');
        for (const o of sel.options) {
          if (o.value && value.toLowerCase().includes(o.value.toLowerCase().split('/')[0].trim())) {
            sel.value = o.value; renderChecklistPhases(); break;
          }
        }
        return;
      }
      if (key === 'BIZ_MODEL') { document.getElementById('cl-biz-model').value = value; return; }
      if (key === 'MAIN_RISK')  { document.getElementById('cl-biz-risk').value  = value; return; }

      const parts = value.split('|').map(x => x.trim());
      const ans  = parts[0];
      const conf = parts[1] || 'medium';
      const ev   = parts.slice(2).join('|').trim();
      const clean = (!ans || ans === 'null') ? null : ans;

      if (key.startsWith('hs') && typeof clHardStopState !== 'undefined' && clHardStopState.hasOwnProperty(key) && clean) {
        clHardStopState[key] = clean;
        if (clean === 'yes') {
          clHardStopTriggered = true;
          const h = CL_HARD_STOPS.find(x => x.id === key);
          clHardStopText = h ? h.text : 'Hard stop triggered.';
        }
      } else if (typeof clState !== 'undefined' && clState.hasOwnProperty(key) && clean) {
        clState[key] = clean;
        window.aiFilledItems[key] = { confidence: conf, evidence: ev };
        n++;
      }
    });

    renderChecklistPhases();
    updateCLScore();
    label.innerHTML = `${n} items filled — review before saving<span style="display:block;font-size:11px;margin-top:3px;color:var(--text3)">Green AI = high confidence · Yellow AI = verify</span>`;
    showToast(`✨ ${n} items filled from PDF`);

  } catch(err) {
    console.error('PDF parse error:', err);
    showToast('Error: ' + err.message);
    label.innerHTML = '📄 Upload StockLens Analysis PDF<span style="display:block;font-size:11px;margin-top:3px;color:var(--text3)">Generated by Claude</span>';
  }
  input.value = '';
}
