// StockLens PDF Upload — self-injects upload button, no index.html change needed

(function injectPdfUploadButton() {
  function tryInject() {
    const labels = document.querySelectorAll('p.section-label');
    const bizLabel = [...labels].find(el => el.textContent.includes('Business Understanding'));
    if (!bizLabel) return false;
    if (document.getElementById('pdf-upload')) return true;
    const wrapper = document.createElement('div');
    wrapper.style.cssText = 'margin:0 16px 12px';
    wrapper.innerHTML = '<label for="pdf-upload" id="pdf-upload-label" style="display:block;width:100%;padding:12px 16px;background:var(--surface);border:2px dashed var(--border2);border-radius:var(--r);text-align:center;cursor:pointer;color:var(--text2);font-size:13px;font-family:inherit">📄 Upload StockLens Analysis PDF<span style=\'display:block;font-size:11px;margin-top:3px;color:var(--text3)\'>Generated by Claude — auto-fills checklist</span></label><input type="file" id="pdf-upload" accept=".pdf" style="display:none" onchange="handlePdfUpload(this)">';
    bizLabel.parentNode.insertBefore(wrapper, bizLabel);
    return true;
  }
  if (!tryInject()) {
    const obs = new MutationObserver(() => { if (tryInject()) obs.disconnect(); });
    obs.observe(document.body, { childList: true, subtree: true });
  }
  document.addEventListener('click', () => setTimeout(tryInject, 400));
})();

async function handlePdfUpload(input) {
  const file = input.files[0];
  if (!file) return;
  const label = document.getElementById('pdf-upload-label');
  label.textContent = 'Reading PDF...';
  try {
    pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://unpkg.com/pdfjs-dist@3.11.174/build/pdf.worker.min.js';
    const arrayBuffer = await file.arrayBuffer();
    const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
    let fullText = '';
    for (let i = 1; i <= pdf.numPages; i++) {
      const page = await pdf.getPage(i);
      const tc = await page.getTextContent();
      fullText += tc.items.map(x => x.str).join(' ') + '\n';
    }
    const s = fullText.indexOf('=== STOCKLENS DATA ===');
    const e = fullText.indexOf('=== END DATA ===');
    if (s === -1 || e === -1) {
      showToast('No StockLens data block found');
      label.innerHTML = '📄 Upload StockLens Analysis PDF<span style="display:block;font-size:11px;margin-top:3px;color:var(--text3)">Generated by Claude</span>';
      return;
    }
    const lines = fullText.substring(s+22,e).trim().split('\n').map(l=>l.trim()).filter(l=>l);
    let n = 0; window.aiFilledItems = {};
    for (const line of lines) {
      if (line.startsWith('STOCK:'))    { document.getElementById('cl-stock').value=line.replace('STOCK:','').trim(); continue; }
      if (line.startsWith('SECTOR:'))   { const v=line.replace('SECTOR:','').trim(); const sel=document.getElementById('cl-sector'); for (const o of sel.options){if(o.value&&v.toLowerCase().includes(o.value.toLowerCase().split('/')[0].trim())){sel.value=o.value;renderChecklistPhases();break;}} continue; }
      if (line.startsWith('BIZ_MODEL:')){document.getElementById('cl-biz-model').value=line.replace('BIZ_MODEL:','').trim();continue;}
      if (line.startsWith('MAIN_RISK:')){document.getElementById('cl-biz-risk').value=line.replace('MAIN_RISK:','').trim();continue;}
      const m=line.match(/^(p\d+_\d+|hs\d+_\d+):/); if(!m)continue;
      const id=m[1]; const parts=line.slice(id.length+1).split('|').map(x=>x.trim());
      const ans=parts[0]; const conf=parts[1]||'medium'; const ev=parts.slice(2).join('|').trim();
      const clean=(!ans||ans==='null')?null:ans;
      if(id.startsWith('hs')&&typeof clHardStopState!=='undefined'&&clHardStopState.hasOwnProperty(id)&&clean){
        clHardStopState[id]=clean;
        if(clean==='yes'){clHardStopTriggered=true;const h=CL_HARD_STOPS.find(x=>x.id===id);clHardStopText=h?h.text:'Hard stop.';}
      } else if(typeof clState!=='undefined'&&clState.hasOwnProperty(id)&&clean){
        clState[id]=clean; window.aiFilledItems[id]={confidence:conf,evidence:ev}; n++;
      }
    }
    renderChecklistPhases(); updateCLScore();
    label.innerHTML = n+' items filled - review before saving<span style="display:block;font-size:11px;margin-top:3px;color:var(--text3)">Green AI = high confidence / Yellow AI = verify</span>';
    showToast(n+' items filled from PDF');
  } catch(err){
    showToast('Error: '+err.message);
    label.innerHTML='📄 Upload StockLens Analysis PDF<span style="display:block;font-size:11px;margin-top:3px;color:var(--text3)">Generated by Claude</span>';
  }
  input.value='';
}// StockLens PDF Upload Feature
async function handlePdfUpload(input) {
  const file = input.files[0];
  if (!file) return;
  const label = document.getElementById('pdf-upload-label');
  label.textContent = 'Reading PDF...';
  try {
    pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://unpkg.com/pdfjs-dist@3.11.174/build/pdf.worker.min.js';
    const ab = await file.arrayBuffer();
    const pdf = await pdfjsLib.getDocument({ data: ab }).promise;
    let txt = '';
    for (let i = 1; i <= pdf.numPages; i++) {
      const pg = await pdf.getPage(i);
      const tc = await pg.getTextContent();
      txt += tc.items.map(x => x.str).join(' ') + '
';
    }
    const s = txt.indexOf('=== STOCKLENS DATA ===');
    const e = txt.indexOf('=== END DATA ===');
    if (s === -1 || e === -1) { showToast('No data block found'); label.innerHTML = '📄 Upload StockLens Analysis PDF'; return; }
    const lines = txt.substring(s+22,e).trim().split('
').map(l=>l.trim()).filter(l=>l);
    let n = 0; window.aiFilledItems = {};
    for (const line of lines) {
      if (line.startsWith('STOCK:'))    { document.getElementById('cl-stock').value=line.replace('STOCK:','').trim(); continue; }
      if (line.startsWith('SECTOR:'))   { const v=line.replace('SECTOR:','').trim(); const sel=document.getElementById('cl-sector'); for (const o of sel.options) { if(o.value&&v.toLowerCase().includes(o.value.toLowerCase().split('/')[0].trim())){sel.value=o.value;renderChecklistPhases();break;} }; continue; }
      if (line.startsWith('BIZ_MODEL:')){document.getElementById('cl-biz-model').value=line.replace('BIZ_MODEL:','').trim();continue;}
      if (line.startsWith('MAIN_RISK:')){document.getElementById('cl-biz-risk').value=line.replace('MAIN_RISK:','').trim();continue;}
      const m=line.match(/^(pd+_d+|hsd+_d+):/); if(!m)continue;
      const id=m[1]; const parts=line.slice(id.length+1).split('|').map(s=>s.trim());
      const ans=parts[0]; const conf=parts[1]||'medium'; const ev=parts.slice(2).join('|').trim();
      const cl=(!ans||ans==='null')?null:ans;
      if(id.startsWith('hs')&&clHardStopState.hasOwnProperty(id)&&cl){clHardStopState[id]=cl;if(cl==='yes'){clHardStopTriggered=true;const h=CL_HARD_STOPS.find(x=>x.id===id);clHardStopText=h?h.text:'Hard stop.';}}
      else if(clState.hasOwnProperty(id)&&cl){clState[id]=cl;window.aiFilledItems[id]={confidence:conf,evidence:ev};n++;}
    }
    renderChecklistPhases();updateCLScore();
    label.innerHTML=n+' items filled - review before saving';
    showToast(n+' items filled from PDF');
  } catch(e){showToast('Error: '+e.message);label.innerHTML='📄 Upload StockLens Analysis PDF';}
  input.value='';
}
