// StockLens PDF Upload — self-injects upload button

function tryInjectPdfButton() {
  if (document.getElementById('pdf-upload')) return true;
  const bizLabel = [...document.querySelectorAll('p.section-label')].find(el => el.textContent.includes('Business Understanding'));
  if (!bizLabel) return false;
  const d = document.createElement('div');
  d.style.cssText = 'margin:0 16px 12px';
  d.innerHTML = '<label for="pdf-upload" id="pdf-upload-label" style="display:block;width:100%;padding:12px 16px;background:var(--surface);border:2px dashed var(--border2);border-radius:var(--r);text-align:center;cursor:pointer;color:var(--text2);font-size:13px;font-family:inherit">📄 Upload StockLens Analysis PDF<span style=\'display:block;font-size:11px;margin-top:3px;color:var(--text3)\'>Generated by Claude — auto-fills checklist</span></label><input type="file" id="pdf-upload" accept=".pdf" style="display:none" onchange="handlePdfUpload(this)">';
  bizLabel.parentNode.insertBefore(d, bizLabel);
  return true;
}

function initPdfUpload() {
  if (!tryInjectPdfButton()) {
    const obs = new MutationObserver(() => { if (tryInjectPdfButton()) obs.disconnect(); });
    obs.observe(document.body, { childList: true, subtree: true });
  }
  document.addEventListener('click', () => setTimeout(tryInjectPdfButton, 400));
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initPdfUpload);
} else { initPdfUpload(); }

async function handlePdfUpload(input) {
  const file = input.files[0]; if (!file) return;
  const label = document.getElementById('pdf-upload-label');
  label.textContent = 'Reading PDF...';
  try {
    pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://unpkg.com/pdfjs-dist@3.11.174/build/pdf.worker.min.js';
    const pdf = await pdfjsLib.getDocument({ data: await file.arrayBuffer() }).promise;
    let txt = '';
    for (let i = 1; i <= pdf.numPages; i++) {
      const pg = await pdf.getPage(i);
      const tc = await pg.getTextContent();
      txt += tc.items.map(x => x.str).join(' ') + '\n';
    }

    const s = txt.indexOf('=== STOCKLENS DATA ===');
    const e = txt.indexOf('=== END DATA ===');
    if (s === -1 || e === -1) {
      showToast('No StockLens data block found in PDF');
      label.innerHTML = '📄 Upload StockLens Analysis PDF<span style="display:block;font-size:11px;margin-top:3px;color:var(--text3)">Generated by Claude</span>';
      return;
    }

    const blockContent = txt.substring(s + 22, e).trim();

    // KEY FIX: PDF.js joins all text with spaces — no newlines preserved.
    // Split by item ID pattern using lookahead instead of \n.
    const lines = blockContent
      .split(/(?=(?:STOCK|SECTOR|BIZ_MODEL|MAIN_RISK|hs\d+_\d+|p\d+_\d+):)/)
      .map(l => l.trim())
      .filter(l => l.length > 0);

    let n = 0;
    window.aiFilledItems = {};

    for (const line of lines) {
      if (line.startsWith('STOCK:'))    { document.getElementById('cl-stock').value    = line.replace('STOCK:','').trim();    continue; }
      if (line.startsWith('SECTOR:'))   {
        const v = line.replace('SECTOR:','').trim();
        const sel = document.getElementById('cl-sector');
        for (const o of sel.options) {
          if (o.value && v.toLowerCase().includes(o.value.toLowerCase().split('/')[0].trim())) {
            sel.value = o.value; renderChecklistPhases(); break;
          }
        }
        continue;
      }
      if (line.startsWith('BIZ_MODEL:')){ document.getElementById('cl-biz-model').value = line.replace('BIZ_MODEL:','').trim(); continue; }
      if (line.startsWith('MAIN_RISK:')){ document.getElementById('cl-biz-risk').value  = line.replace('MAIN_RISK:','').trim();  continue; }

      const m = line.match(/^(hs\d+_\d+|p\d+_\d+):/);
      if (!m) continue;

      const id    = m[1];
      const rest  = line.slice(id.length + 1).trim();
      const parts = rest.split('|').map(x => x.trim());
      const ans   = parts[0];
      const conf  = parts[1] || 'medium';
      const ev    = parts.slice(2).join('|').trim();
      const clean = (!ans || ans === 'null') ? null : ans;

      if (id.startsWith('hs') && typeof clHardStopState !== 'undefined' && clHardStopState.hasOwnProperty(id) && clean) {
        clHardStopState[id] = clean;
        if (clean === 'yes') {
          clHardStopTriggered = true;
          const h = CL_HARD_STOPS.find(x => x.id === id);
          clHardStopText = h ? h.text : 'Hard stop triggered by PDF analysis.';
        }
      } else if (typeof clState !== 'undefined' && clState.hasOwnProperty(id) && clean) {
        clState[id] = clean;
        window.aiFilledItems[id] = { confidence: conf, evidence: ev };
        n++;
      }
    }

    renderChecklistPhases();
    updateCLScore();
    label.innerHTML = n + ' items filled — review before saving<span style="display:block;font-size:11px;margin-top:3px;color:var(--text3)">🟢 AI = high confidence · 🟡 AI = verify · blank = check manually</span>';
    showToast('✨ ' + n + ' items filled from PDF');

  } catch(err) {
    console.error('PDF parse error:', err);
    showToast('Error: ' + err.message);
    label.innerHTML = '📄 Upload StockLens Analysis PDF<span style="display:block;font-size:11px;margin-top:3px;color:var(--text3)">Generated by Claude</span>';
  }
  input.value = '';
}
